# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read2

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 19 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ1: ${{ secrets.YOUTH_READ311 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ312 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ321 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ322 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ411 }}
      YOUTH_READ6: ${{ secrets.YOUTH_READ412 }}
      YOUTH_READ7: ${{ secrets.YOUTH_READ421 }}
      YOUTH_READ8: ${{ secrets.YOUTH_READ422 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ1
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ311 }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ312 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ321 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ322 }}
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ5
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ411 }}
                    
      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ6
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ412 }}
          
      - name: '运行 【中青看点自动阅读七】'
        if: env.YOUTH_READ7
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ421 }}
          
      - name: '运行 【中青看点自动阅读八】'
        if: env.YOUTH_READ8
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ422 }}
